### ISSUE TITLE
Outside parameters shown as syntax error but in fact they are not

### ISSUE THREAD

**Issue by FarukHarmanli** [abaplint/vscode-abaplint#40]
Do we have solution here? especially I have this kind of issue, if FM has include. For example FM has some parameters and if this parameters are used in include, abaplint thinks that there is syntax error but in fact there is no syntax error

![1](https://user-images.githubusercontent.com/58327574/70916308-c20c1900-201b-11ea-8aeb-f5b92c62ff4e.jpg)
![2](https://user-images.githubusercontent.com/58327574/70916311-c2a4af80-201b-11ea-8dce-43286edd43db.jpg)

_Originally posted by @FarukHarmanli in https://github.com/abaplint/vscode-abaplint/issues/33#issuecomment-566093362_

**Comment by larshp** [comment]
yea, so the code for function module EXIT_SAPMM06E_012 is probably not in git, you can choose to do this, but as a general best practice I'd recommend putting as little amount of code into the ZXM06U43 include.

So the contents of the include becomes something like:
```abap
new zcl_logic( )->run(
  exporting
   is_ekko = i_ekko
  changing
   ct_ekpo = tekpo ).
```
and implement the logic inside `zcl_logic`, this will also help for syntax checking the business logic and for code inspector. However, the errors for ZXM06U43 will still be there, but since there is no real logic in it, it is quite safe to exclude it from the rule, each rule has an `exclude` parameter that can be used to exclude files, example: https://github.com/larshp/abapGit/blob/master/abaplint.json#L68

If you cannot refactor the code, you can still choose to exclude the include from the rule

**Comment by larshp** [comment]
@FarukHarmanli did above help?

**Comment by larshp** [comment]
closing
